package consts

const K_CONFIG_FILE = "K_CONFIG_FILE"
const K_PRINT_FORMATTED_JSON = "K_PRINT_FORMATTED_JSON"
const K_NO_ELLIPSIS = "K_NO_ELLIPSIS"
const K_PRINT_BODY_OF_ADDED = "K_PRINT_BODY_OF_ADDED"
